name: CD

on:
  push:
    branches:
      - develop

jobs:
  staging:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: "12"

      - uses: actions/checkout@v2

      - run: npm ci

      - run: npm test -- --coverage
        env:
          CI: true

      - run: npm run build

      - name: deploy on stage
        run: npx surge --project ./build --domain aulafjn-cicd.surge.sh
        env:
          SURGE_LOGIN: ${{secrets.SURGE_LOGIN}}
          SURGE_TOKEN: ${{secrets.SURGE_TOKEN}}
