name: CI

on:
  pull_request:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: check node version
        run: |
          node --version
          npm --version
