name: CI

on:
  pull_request:
    branches: [develop]
  push:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: check node version
        run: |
          node --version
          npm --version

      - name: project checkout
        uses: actions/checkout@v2

      - name: listing files
        run: ls -l
